Adafruit_NeoTrellis trellis;

int MODE_PAD_A_INDEX = 0;
int MODE_PAD_B_INDEX = 3;
int MODE_PAD_C_INDEX = 12;
int MODE_PAD_D_INDEX = 15;

int PLAY_BUTTON_PIN = A0;
int CLOCK_INPUT_PIN = A2;

int CLOCK_LED_PIN = 12;

int VOICE_A_PIN = 2;
int VOICE_B_PIN = 3;
int VOICE_C_PIN = 4;
int VOICE_D_PIN = 5;

int COLOR_NONE = 0x000000;
int COLOR_PURPLE = 0x590696;
int COLOR_BLUE = 0x37E2D5;
int COLOR_PINK = 0xC70A80;
int COLOR_GOLD = 0xFBCB0A;

int COLOR_MODE_KEY = 0xF55353;
